version: '3.8'

services:
  app:
    image: your-dockerhub-username/fastapi-app:latest
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
