name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Deploy to AWS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
          AWS_USER: ${{ secrets.AWS_USER }}
          AWS_IP: ${{ secrets.AWS_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no $AWS_USER@$AWS_IP << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          docker-compose down
          docker-compose up -d
          EOF
        shell: bash